<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Citect.TrnFiles\Citect.TrnFiles.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <None Update="data\E_MOT1_0\IsStarted\IsStarted.000">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="data\E_MOT1_0\IsStarted\IsStarted.001">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="data\E_MOT1_0\IsStarted\IsStarted.002">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="data\E_MOT1_0\IsStarted\IsStarted.HST">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="data\IO_AI_EX_0\Out\Out.000">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="data\IO_AI_EX_0\Out\Out.001">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="data\IO_AI_EX_0\Out\Out.002">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="data\IO_AI_EX_0\Out\Out.HST">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="data\Out.000">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="data\Out.001">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="data\Out.002">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="data\Out.HST">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
